# Generated by Django 4.0.3 on 2022-04-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='male', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='stu_class',
            field=models.CharField(max_length=20),
        ),
    ]
