# Generated by Django 4.0.3 on 2022-04-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='stu_name',
            field=models.CharField(max_length=20),
        ),
    ]
