# Generated by Django 4.0.3 on 2022-04-27 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_title', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_title', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=150, verbose_name='标题')),
                ('comments', models.IntegerField(default=0, verbose_name='评价数')),
                ('likes', models.IntegerField(default=0, verbose_name='点赞数')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价钱')),
                ('visits', models.IntegerField(default=0, verbose_name='浏览量')),
                ('collect_num', models.IntegerField(default=0, verbose_name='收藏量')),
                ('is_launched', models.BooleanField(default=True, verbose_name='是否上架销售')),
                ('default_image', models.ImageField(blank=True, default='', max_length=200, null=True, upload_to='', verbose_name='默认图片')),
                ('word', models.TextField(verbose_name='文字介绍')),
                ('Buyers', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='goods_buyer', to=settings.AUTH_USER_MODEL, verbose_name='买家')),
            ],
            options={
                'verbose_name': '商品主要',
                'verbose_name_plural': '商品主要',
                'db_table': 'tb_goods',
            },
        ),
        migrations.CreateModel(
            name='GoodsVisitCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_title', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_title', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('count', models.IntegerField(default=0, verbose_name='访问量')),
                ('date', models.DateField(auto_now_add=True, verbose_name='统计日期')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goods', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品访问量',
                'verbose_name_plural': '商品访问量',
                'db_table': 'tb_goods_visit',
            },
        ),
        migrations.CreateModel(
            name='GoodsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_title', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_title', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('image', models.ImageField(upload_to='', verbose_name='图片')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goods', verbose_name='Goods')),
            ],
            options={
                'verbose_name': '商品图片',
                'verbose_name_plural': '商品图片',
                'db_table': 'tb_Goods_image',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_title', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_title', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=10, verbose_name='名称')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='goods.goodscategory', verbose_name='父类别')),
            ],
            options={
                'verbose_name': '商品类别',
                'verbose_name_plural': '商品类别',
                'db_table': 'tb_goods_category',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.goodscategory', verbose_name='商品类别'),
        ),
        migrations.AddField(
            model_name='goods',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_user', to=settings.AUTH_USER_MODEL, verbose_name='卖家'),
        ),
    ]
