# Generated by Django 4.0.3 on 2022-04-27 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0002_remove_goods_default_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='Buyers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_buyer', to=settings.AUTH_USER_MODEL, verbose_name='买家'),
        ),
    ]
