# Generated by Django 4.0.3 on 2022-04-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_goods_buyers'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='defaultimg',
            field=models.ImageField(default='', upload_to='', verbose_name='默认图片'),
        ),
    ]
