# Generated by Django 4.0.3 on 2022-04-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_goods_defaultimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='defaultimg',
            field=models.ImageField(upload_to='', verbose_name='默认图片'),
        ),
    ]
