# Generated by Django 4.0.3 on 2022-04-28 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_alter_goods_defaultimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='create_title',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='update_title',
            new_name='update_time',
        ),
        migrations.RenameField(
            model_name='goodscategory',
            old_name='create_title',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='goodscategory',
            old_name='update_title',
            new_name='update_time',
        ),
        migrations.RenameField(
            model_name='goodsimage',
            old_name='create_title',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='goodsimage',
            old_name='update_title',
            new_name='update_time',
        ),
        migrations.RenameField(
            model_name='goodsvisitcount',
            old_name='create_title',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='goodsvisitcount',
            old_name='update_title',
            new_name='update_time',
        ),
    ]
