# Generated by Django 4.0.3 on 2022-04-27 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_title', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_title', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goods', verbose_name='商品')),
                ('goods_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_user', to=settings.AUTH_USER_MODEL, verbose_name='卖家')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_buyer', to=settings.AUTH_USER_MODEL, verbose_name='买家')),
            ],
            options={
                'verbose_name': '聊天主要',
                'verbose_name_plural': '聊天主要',
                'db_table': 'tb_chatting',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_title', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_title', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('text', models.TextField(verbose_name='聊天内容')),
                ('chatting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatting', verbose_name='聊天室')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发送者')),
            ],
            options={
                'verbose_name': '聊天信息',
                'verbose_name_plural': '聊天信息',
                'db_table': 'tb_chat_message',
            },
        ),
    ]
