# Generated by Django 4.0.3 on 2022-05-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_create_title_chatmessage_create_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='brecever',
            field=models.BooleanField(default=False, verbose_name='接受者看了吗'),
        ),
    ]
