# Generated by Django 4.0.3 on 2022-05-05 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_chatmessage_recever_alter_chatmessage_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatting',
            name='brecever',
            field=models.BooleanField(default=False, verbose_name='接受者看了吗'),
        ),
        migrations.AddField(
            model_name='chatting',
            name='recever',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chat_recever', to=settings.AUTH_USER_MODEL, verbose_name='接收者'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatting',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sender', to=settings.AUTH_USER_MODEL, verbose_name='发送者'),
            preserve_default=False,
        ),
    ]
